import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useEffect, useState } from "react";
import { useQuery } from '@apollo/client'
import GET_TRANSFERS from './graphql/queries'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { loading, error, data } = useQuery(GET_TRANSFERS)
  const [eventList, setEventList] = useState<History[]>([])
  const [nftTransfers, setTokenHolders] = useState([]);
  
  useEffect(() => {
    if (!loading && !error && data) {
      setTokenHolders(data.transfers);
      console.log(data);
    }
  }, [loading, error, data]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {nftTransfers.map((nftTransfer) => (
            <div key={nftTransfer.id} style={{ margin: "20px" }}>
              <div>トークンID： {nftTransfer.tokenId}</div>
              <div>送信者： {nftTransfer.from}</div>
              <div>受信者： {nftTransfer.from}</div>
            </div>
          ))}
        </div>
      </main>
    </>
  )
}
